version: '2'
services:
  phpfpm:
    image: antswordproject/antsword-labs:php-7.2.18-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/start.sh:/start.sh
    command: /bin/sh /start.sh
  nginx:
    image: nginx:1.17
    depends_on:
      - phpfpm
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/start.sh:/start.sh
    command: /bin/sh /start.sh
    ports:
      - "18080:80"
      - "18443:443"
